apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mediawiki.names.fullname" . }}
  labels:
    {{- include "labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.mediawikiPassword }}
  mediawiki-password: {{ .Values.mediawikiPassword | b64enc | quote }}
  {{- else }}
  mediawiki-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  
