# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Add labels to all the deployed resources
##
commonLabels: {}

## Add annotations to all the deployed resources
##
commonAnnotations: {}

image:
  name: mysql
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 5.6

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

containerSecurityContext:
  enabled: false
  #runAsUser: 1001

password: "password"

securityContext: {}

service:
  type: "LoadBalancer"
  port: 3306
  loadBalancerIP: ""

resources: {}

## Extra volumes to add to the deployment
##
extraVolumes: []

## Extra volume mounts to add to the container
##
extraVolumeMounts: []

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 8Gi

nodeSelector: {}

tolerations: []

affinity: {}
